steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-logger', '-f', 'Dockerfile.test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/test-logger']
images:
- 'gcr.io/$PROJECT_ID/test-logger'