-- The Sun Room - Waitlist Table Schema

CREATE TABLE public.waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS for the waitlist table
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Allow public access to insert their email into the waitlist
CREATE POLICY "Allow public insert access to waitlist" ON public.waitlist FOR INSERT WITH CHECK (true);
