import os
import sys
import logging
from dotenv import load_dotenv
from supabase import create_client
import os

# Explicitly load .env from the project root
load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../.env'))

# Add project root to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from worker.src.agents.illustrator import IllustratorAgent
from llm.client import LLMClient

# Setup
load_dotenv()
logging.basicConfig(level=logging.INFO)

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    print("Missing Supabase credentials")
    sys.exit(1)

db_client = create_client(SUPABASE_URL, SUPABASE_KEY)
llm_client = LLMClient()

# Use the same IDs from the successful Storybook test
USER_ID = "57a5073f-6dc5-4b92-ad9b-925d01f8e88d"
# We need the ID of the NEW trailhead created by the Storybook Agent.
# Since we can't dynamically grab it easily in this static script without querying,
# I will query for the most recent storybook manifest.

def get_latest_storybook_id():
    # Targeting the specific Saga ID generated by test_saga.py
    return "8131ca68-7373-4ab7-9cdd-ebce0f8106cb"

def run_test():
    print(f"Running IllustratorAgent test...")
    
    trailhead_id = get_latest_storybook_id()
    if not trailhead_id:
        print("No Storybook Manifest found. Run test_storybook.py first.")
        return

    print(f"User: {USER_ID}")
    print(f"Trailhead (Manifest): {trailhead_id}")
    
    print(f"DEBUG test_illustrator: GEMINI_API_KEY env: {os.environ.get("GEMINI_API_KEY")}")
    print(f"DEBUG test_illustrator: GCP_PROJECT_ID env: {os.environ.get("GCP_PROJECT_ID")}")
    print(f"DEBUG test_illustrator: GCP_LOCATION env: {os.environ.get("GCP_LOCATION")}")
    
    agent = IllustratorAgent(db=db_client, worker=None, llm=llm_client)
    agent.run_task(user_id=USER_ID, trailhead_id=trailhead_id, provider="mock")
    
    print("Illustration complete. Checking results...")
    
    # Verify
    res = db_client.table("Trailheads").select("content").eq("id", trailhead_id).single().execute()
    content = res.data.get('content', {})
    pages = content.get('pages', [])
    
    if pages and 'image_url' in pages[0]:
        print(f"Success! Page 1 Image URL: {pages[0]['image_url']}")
        print(f"Asset Refs: {content.get('asset_references')}")
    else:
        print("Failed to update manifest with images.")

if __name__ == "__main__":
    run_test()
