import os
import sys
import logging
from dotenv import load_dotenv
from supabase import create_client

# Add project root to path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from worker.src.agents.publisher import PublisherAgent

# Setup
load_dotenv()
logging.basicConfig(level=logging.INFO)

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    print("Missing Supabase credentials")
    sys.exit(1)

db_client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Use the IDs from the previous steps
USER_ID = "57a5073f-6dc5-4b92-ad9b-925d01f8e88d"

def get_latest_storybook_id():
    # Targeting the specific Saga ID generated by test_saga.py
    return "8131ca68-7373-4ab7-9cdd-ebce0f8106cb"

def run_test():
    print(f"Running PublisherAgent test...")
    
    trailhead_id = get_latest_storybook_id()
    if not trailhead_id:
        print("No Storybook Manifest found. Run test_illustrator.py first.")
        return

    print(f"User: {USER_ID}")
    print(f"Trailhead: {trailhead_id}")
    
    agent = PublisherAgent(db=db_client)
    agent.run_task(user_id=USER_ID, trailhead_id=trailhead_id)
    
    print("Publishing process initiated.")

if __name__ == "__main__":
    run_test()
