import logging
import json
from datetime import datetime, timedelta, date
from typing import List
from .base import BaseAgent
from db import crud, schemas

logger = logging.getLogger(__name__)

class DistillerAgent(BaseAgent):
    """
    The Alchemist.
    Compresses raw episodic atoms into high-level Semantic Memories (Summaries).
    Implements the Map-Reduce logic from MirrorMind Sec 2.2.2.
    """

    def run_task(self, user_id: str, time_window: str = 'monthly'):
        logger.info(f"⚗️ Distiller started for User {user_id} ({time_window})")
        
        # 1. Calculate Date Range
        end_date = datetime.now()
        if time_window == 'monthly':
            start_date = end_date - timedelta(days=30)
        elif time_window == 'yearly':
            start_date = end_date - timedelta(days=365)
        else:
            logger.error(f"Invalid time_window: {time_window}")
            return

        # 2. Fetch Atoms
        atoms = crud.get_atoms_by_date_range(self.db, user_id, start_date.isoformat(), end_date.isoformat())
        
        if not atoms:
            logger.info("No atoms found in this window. Distiller sleeping.")
            return

        logger.info(f"Found {len(atoms)} atoms to distill.")

        # 3. Map-Reduce Summarization
        summary = self._summarize_atoms(atoms)
        
        # 4. Evolution Insight (Compare with previous)
        previous_memory = crud.get_recent_semantic_memory(self.db, user_id, time_window)
        evolution_insight = "Initial distillation."
        
        if previous_memory:
            evolution_insight = self._generate_evolution_insight(previous_memory.summary_text, summary)

        # 5. Embedding
        embedding = self.llm.get_embedding(summary)

        # 6. Store
        memory = schemas.SemanticMemory(
            user_id=user_id,
            time_window=time_window,
            window_start=start_date,
            window_end=end_date,
            summary_text=summary,
            evolution_insight=evolution_insight,
            embedding=embedding
        )
        
        crud.create_semantic_memory(self.db, memory)
        logger.info(f"Distillation complete. Insight: {evolution_insight[:50]}...")

    def _summarize_atoms(self, atoms: List[schemas.Atom]) -> str:
        """
        Compresses a list of atoms into a cohesive narrative summary.
        Handles large lists via chunking.
        """
        # Convert atoms to text representation
        atom_texts = [f"- [{a.type}] {a.name}: {a.content}" for a in atoms]
        full_text = "\n".join(atom_texts)
        
        # Simple Chunking Strategy
        chunk_size = 10000 # Characters approx
        chunks = [full_text[i:i+chunk_size] for i in range(0, len(full_text), chunk_size)]
        
        partial_summaries = []
        
        prompt_template = """
        You are a Cognitive Distiller. Analyze the following stream of thoughts (Atoms) generated by a user over time.
        Synthesize them into a high-level semantic summary. 
        Focus on:
        1. Key recurring themes.
        2. Shifts in interest.
        3. Major questions asked.
        
        Input Atoms:
        {text}
        
        Summary:
        """
        
        for i, chunk in enumerate(chunks):
            try:
                resp = self.llm.chat_completion(prompt_template.format(text=chunk))
                partial_summaries.append(resp)
            except Exception as e:
                logger.error(f"Error summarizing chunk {i}: {e}")
        
        if len(partial_summaries) == 1:
            return partial_summaries[0]
            
        # Reduce Step
        combined_summaries = "\n".join(partial_summaries)
        final_prompt = f"""
        Combine these partial summaries into a single, cohesive narrative of the user's recent intellectual journey.
        
        {combined_summaries}
        
        Final Distilled Summary:
        """
        return self.llm.chat_completion(final_prompt)

    def _generate_evolution_insight(self, old_summary: str, new_summary: str) -> str:
        prompt = f"""
        Compare the User's thinking from the Previous Period to the Current Period.
        
        Previous Summary:
        {old_summary}
        
        Current Summary:
        {new_summary}
        
        Identify 3 key shifts in perspective, topic, or complexity. How has the user's mind evolved?
        Output a concise insight (max 50 words).
        """
        return self.llm.chat_completion(prompt)
