steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',
      '-t', '$_IMAGE_NAME',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY',
      '--build-arg', 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL',
      '.'
    ]
images:
  - '$_IMAGE_NAME'
substitutions:
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/thesunroom-476921/sunroom-repo/sunroom-web:latest'
  _NEXT_PUBLIC_SUPABASE_URL: 'https://fbzrobgstwkxwcsomtur.supabase.co'
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZienJvYmdzdHdreHdjc29tdHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NTMzNzUsImV4cCI6MjA3ODQyOTM3NX0.jbUArhNqNqJ3CIFdPkp2PNrreOrxgtom8AwdSzoXnCM'
  _NEXT_PUBLIC_API_URL: 'https://sunroom-api-136102377810.us-central1.run.app'
